language: emacs-lisp

node_js:
  - "0.10"

env:
  - EVM_EMACS=emacs-24.3-bin
  - EVM_EMACS=emacs-24.4-bin
  - EVM_EMACS=emacs-24.5-bin

before_install:
  - sudo mkdir /usr/local/evm
  - sudo chown travis:travis /usr/local/evm
  - export PATH="/home/travis/.cask/bin:$PATH"
  - export PATH="/home/travis/.evm/bin:$PATH"
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - evm install ${EVM_EMACS} --use
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - cask
  - npm install -g scopifier

script:
  - emacs --version
  - make test
