# https://github.com/rolandwalker/emacs-travis

language: emacs-lisp

node_js:
  - "0.10"

env:
  matrix:
    - EMACS=emacs24

install:
  - if [ "$EMACS" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el;
    fi
  - curl -fsSL https://raw.github.com/cask/cask/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
  - npm install -g scopifier

script:
  make test EMACS=${EMACS}
